providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm install -g pnpm@9.15.0 && pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["export PATH=\"$(npm bin -g):$PATH\" && pnpm run build"]

[start]
cmd = "export PATH=\"$(npm bin -g):$PATH\" && pnpm run start"
